Posts/urls.py
from django.urls import path
from Posts.views import Postcreateview, Postdetailview, Postdeleteview

app_name = 'Posts'

urlpatterns = [
    path('detail/<int:pk>/',Postdetailview.as_view(),name='detail-view'),
    path('create/',Postcreateview.as_view(),name='create-post'),
    path('<pk>/delete',Postdeleteview.as_view(),name='delete-post'),
]

Social_media/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
    path('post/',include('Posts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('^oauth/', include('social_django.urls', namespace='social')), 
]

user/urls.py
from django.urls import path
from user.views import home, register, profile,profileupdate, Postlistview
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name='user'

urlpatterns = [
    path('',Postlistview.as_view(),name='home'),
    path('register/',register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='Logout.html'),name='logout'),
    path('profile/',profile,name='profile'),
    path('profile_update/',profileupdate,name='profile_update'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='Forgotpwd.html'),name='password_reset'),
    path('password-reset/done',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Groups/models.py
from django.db import models

# Create your models here.

Posts/models.py
from django.db import models
from django.db.models.fields import CharField, TextField, DateTimeField
from django.utils import timezone
from django.db.models.fields.related import ForeignKey
from django.contrib.auth.models import User
from django.urls.base import reverse

# Create your models here.
class Createpost(models.Model):
    title=CharField(max_length=100)
    content=TextField()
    date_posted=DateTimeField(default=timezone.now)
    author=ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.title
# this function is used to redirect the page after the creating the post successfully
    def get_absolute_url(self):
        return reverse('user:home')
    

user/models.py
from django.db import models
from django.db.models.fields.related import OneToOneField
from django.contrib.auth.models import User

# Create your models here.
class ProfileImage(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='default.jpg',upload_to='profile_pics',null=True)
    
    def __str__(self):
        # returning username form the from the profile image module
        return f'{self.user.username} ProfileImage'

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import ProfileImage

class Userregistrationform(UserCreationForm):
    email=forms.EmailField
    class Meta():
        model=User
        fields=['username','email','password1','password2']

class Userupdateform(forms.ModelForm):
    email=forms.EmailField
    class Meta():
        model=User
        fields=['username','email']


class Forgotpwdform(forms.ModelForm):
    email=forms.EmailField
    class Meta():
        model=User
        fields=['username','email']
        

        
class Profileimageform(forms.ModelForm):
    class Meta():
        model= ProfileImage
        fields=['image']

Groups/views.py
from django.shortcuts import render

# Create your views here.

Posts/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView,DetailView,DeleteView
from Posts.models import Createpost
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from rest_framework import filters, generics
from rest_framework.filters import SearchFilter, OrderingFilter
# Create your views here.

class Postcreateview(LoginRequiredMixin,CreateView):
    model = Createpost
    fields = ['title','content']
    template_name='Create_Post.html'
    
    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class Postdetailview(LoginRequiredMixin,DetailView):
    model=Createpost
    template_name='Post_detailview.html'

class Postdeleteview(LoginRequiredMixin,DeleteView):
    model= Createpost
    template_name='Delete_post.html'
    success_url ="/"
    
class Searchposts(generics.ListAPIView):
    querry=Createpost.objects.all()
    #serializer_class = CreatepostSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ['title','content','author__username']

user/views.py
from django.shortcuts import render, redirect
from user.forms import Userregistrationform,Profileimageform, Userupdateform,\
    Forgotpwdform
from Posts.models import Createpost
from django.contrib.auth.models import User
from django.views.generic import  ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
    
    context={'post':Createpost.objects.all()
             }
    return render(request,'home.html',context)

class Postlistview(LoginRequiredMixin,ListView):
    model=Createpost 
    template_name='home.html'
    context_object_name = 'post'
    ordering=['-date_posted']

def register(request):
    if request.method == 'POST':
        form=Userregistrationform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('user:login')
    else:
        form=Userregistrationform()
    return render(request,'registration.html',{'context':form})

@login_required
def profile(request):
    user = request.user
    author = Createpost.author
    context = {
                'post':Createpost.objects.filter(author=user)
        }
    return render(request,'profile.html',context)
    
@login_required
def profileupdate(request):# function to update user profile 
    if request.method == 'POST':
        u_form = Userupdateform(request.POST, instance=request.user)
        p_form = Profileimageform(request.POST, request.FILES, instance=request.user.profileimage)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('user:profile')
    else:
        u_form = Userupdateform(instance=request.user)
        p_form = Profileimageform(instance= request.user.profileimage)
        
    context= {         
    'u_form':u_form,
    'p_form':p_form
            
    }
    return render(request,'Update_profile.html',context)

Posts/templates/Create_Post.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	
		<form method="post">
		{% csrf_token %}
				<br><br><fieldset>
				<legend>Create New Post</legend>
					<!-- form is a inbuilt keyword which does'nt need any passing of arguments from the 
					create view class  -->
					{{ form|crispy }}
					<br><input class="btn btn-success btn-lg" type="submit" value="Post">
				</fieldset>
		</form>
	
	
	
	
{% endblock content %}

Posts/templates/Delete_post.html
{% extends "Base.html" %}
{% block content %}
		<form method="post">
		{% csrf_token %}
			<h4>Are you sure you want to delete the post:- {{ object.title }}</h4>
			<div style="align:center">
				<br><input class="btn btn-danger" type="submit" value="DELETE" width=100>
				<a class="btn btn-info" href="{% url 'Posts:detail-view' object.id %}">CANCEL</a>
			</div>
		</form>	
		       
{% endblock content %}	

Posts/templates/Post_detailview.html
{% extends "Base.html" %}
{% block content %}
				<article class="media content-section">
		          <div class="media-body">
		            <div class="article-metadata">
		              <a class="mr-2" href="#" style="text-transform: capitalize;">Posted By:  {{ object.author }}</a>
		              <small class="text-muted">{{ object.date_posted }}</small>
		            </div>
		            <img class="rounded-circle float-left article-img" src="{{ object.author.profileimage.image.url }}">
		            <h4><a class="article-title" href="#">{{ object.title }}</a></h4>
		            <p class="article-content">{{ object.content }}</p>
		          {% if object.author == user %}
		          <!-- 	<input class="btn btn-danger" type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete this?')" > -->
		          	<a class="btn btn-danger" href="{% url 'Posts:delete-post' object.id %}">Delete</a> 
		          {% endif %}
		          </div>
        		</article>
{% endblock content %}	

Posts/templates/Search.html
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<p> Kevin </p>
</body>
</html>

templates/Base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Social Media</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		<a class="navbar-brand" href="{% url 'user:home' %}">Social Media</a>
		
		<!-- the below 3 lines are used to create 3 lines button when the screen is at the small size -->
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	 	</button>
	 	
<!-- to use the properties of the above 3 lines here the respective class is used 
collapse navbar-collapse  -->
	 	
		{% if user.is_authenticated %}
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
			 		
			 		<!--   this form tag is used to get the search bar in the navigation bar  -->
					<form class="form-inline my-2 my-lg-0" method="GET">
				      	 <input class="form-control mr-lg-2" type="search" name="search" placeholder="Search" aria-label="Search" style="width:500px " >
				     	 <button class="btn btn-dark my-2 my-sm-0" type="submit">Search</button>
		    		</form>
					
				<!--  below mr refers to margin right -->	
					<ul class="navbar-nav mr-auto">
						<li class="nav-item">
							<a class="nav-link" href="{% url 'user:home' %}">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">About</a>
						</li>
					</ul>
				</div>	
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<div class="navbar-nav ml-auto">
					<ul class="navbar-nav">
						<li class="nav-item"><a class="nav-link" href="{% url 'Posts:create-post' %}">Create Post</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'user:profile' %}" style="text-transform: capitalize;">{{ user.username }}</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}">Logout</a></li>
					</ul>
				</div>
			</div>
		{% else %}
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<div class="navbar-nav ml-auto">
					<ul class="navbar-nav">
						<li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}">Login</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'user:register' %}">Sign Up</a></li>
					</ul>
				</div>
			</div>
		{% endif %}
	</nav>
	<!-- page is divided into 12 column   -->
	<div class="container">
	<!-- page is repsented in the type of row  -->
		<div class="row">
		<!-- dividing the screen for small, medium and large screens -->
			<div class="col-sm-12 col-md-8 col-lg-6">
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

user/templates/Base1.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Social Media</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		<a class="navbar-brand" href="{% url 'user:home' %}">Social Media</a>
		
		<!-- the below 3 lines are used to create 3 lines button when the screen is at the small size -->
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	 	</button>
	 	
<!-- to use the properties of the above 3 lines here the respective class is used 
collapse navbar-collapse  -->
		{% if user.is_authenticated %}
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
	 		<!--   this form tag is used to get the search bar in the navigation bar  -->
			<form class="form-inline my-2 my-lg-0">
		      	 <input class="form-control mr-lg-2" type="search" placeholder="Search" aria-label="Search" style="width:500px " >
		     	 <button class="btn btn-dark my-2 my-sm-0" type="submit">Search</button>
    		</form>
		<!--  below mr refers to margin right -->	
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'user:home' %}">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">About</a>
				</li>
			</ul>
		</div>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<div class="navbar-nav ml-auto">
					<ul class="navbar-nav">
						<li class="nav-item"><a class="nav-link" href="{% url 'Posts:create-post' %}">Create Post</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'user:profile' %}" style="text-transform: capitalize;">{{ user.username }}</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}">Logout</a></li>
					</ul>
				</div>
			</div>
		{% else %}
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<div class="navbar-nav ml-auto">
					<ul class="navbar-nav">
						<li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}">Login</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'user:register' %}">Sign Up</a></li>
					</ul>
				</div>
			</div>
		{% endif %}
	</nav>
	
	
				{% block content %}
				{% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

user/templates/Forgotpwd.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	
		<form method="post">
		{% csrf_token %}
				<br><br><fieldset>
				<legend>Provide details to change the password</legend>
					{{ form|crispy }}
					<br><input class="btn btn-info btn-lg btn-block" type="submit" value="Login">
				</fieldset>
		</form>	
	
	
	
{% endblock content %}

user/templates/Home.html
{% extends "Base.html" %}
{% block content %}
			{% for post in post %}
				<article class="media content-section">
		          <div class="media-body">
		            <div class="article-metadata">
		              <a class="mr-2" href="#" style="text-transform: capitalize;">Posted By:  {{ post.author }}</a>
		              <small class="text-muted">{{ post.date_posted }}</small>
		            </div>
		            <img class="rounded-circle float-left article-img" src = "{{ post.author.profileimage.image.url }}">
		            <h4><a class="article-title" href="{% url  'Posts:detail-view' post.id %}">{{ post.title }}</a></h4>
		            <p class="article-content">{{ post.content }}</p>
		          </div>
        		</article>
        	{% endfor %}
{% endblock content %}

user/templates/Logout.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<h4>You Have Been Logged out successfully</h4>
	
{% endblock content %}

user/templates/Profile.html
{% extends "Base1.html" %}
{% block content %}
				<div class="container">
					<div class="row">
						<div class="col-sm-12 col-md-12 col-lg-3">
							<br><img class="rounded-circle account-img" src="{{ request.user.profileimage.image.url }}">
							<h2 class="account-heading" style="text-transform:capitalize;">{{user.username}}</h2>
							<p class="text-secondary">{{user.email}}</p>
							<a class="btn btn-info" href="{% url 'user:profile_update' %}">Update Profile</a>
						</div>
						<div class="col-sm-12 col-md-8 col-lg-6">
						<h4 style="text-align:center">My Posts</h4>
							{% if post %}
								{% for post in post %}
									<article class="media content-section">
							          <div class="media-body">
							            <div class="article-metadata">
							              <a class="mr-2" href="#" style="text-transform: capitalize;">Posted By:  {{ post.author }}</a>
							              <small class="text-muted">{{ post.date_posted }}</small>
							            </div>
							            <img class="rounded-circle float-left article-img" src = "{{ post.author.profileimage.image.url }}">
							            <h4><a class="article-title" href="{% url  'Posts:detail-view' post.id %}">{{ post.title }}</a></h4>
							            <p class="article-content">{{ post.content }}</p>
							          </div>
					        		</article>
		        				{% endfor %}
		        			{% else %}
		        				<h4> You not posted in social media yet <a href="{% url 'Posts:create-post' %}">Create a Post</a> </h4>
		        			{% endif %}
						</div>
					</div>
				</div>
{% endblock content %}	

user/templates/Registration.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	
		<form method="POST">
		{% csrf_token %}
				<br><br><fieldset>
				<legend>Sign Up</legend>
					{{ context|crispy }}
					<br><input class="btn btn-success btn-lg btn-block" type="submit" value="Register"><br>
				</fieldset>
		</form>
				<a href="{% url 'user:login' %}">Already have an account then login</a>
			
	
	
{% endblock content %}

user/templates/Update_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="container">
			<img class="rounded-circle account-img" src="{{ request.user.profileimage.image.url }}">
			<!-- <div>
				<h2 class="account-heading">{{user.username}}</h2>
				<p class="text-secondary">{{user.email}}</p>
			</div>
 -->
			<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
				<br><br><fieldset>
					<legend>UPDATE PROFILE</legend>
					{{ u_form|crispy }}
					<h5>Upload your profile photo</h5>
					{{ p_form|crispy }}
					<div style="align:center">
						<br><input class="btn btn-success" type="submit" value="UPDATE" width=100>
						<a class="btn btn-info" href="{% url 'user:profile' %}">Cancel</a>
					</div>
				</fieldset>
		</form>
	</div>
{% endblock content %}

user/templates/changepwd.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	
		<form method="post">
		{% csrf_token %}
				<br><br><fieldset>
				<legend>Login In</legend>
					{{ form|crispy }}
					<br><input class="btn btn-info btn-lg btn-block" type="submit" value="Login">
					<br><a href="{% url 'user:forgotpwd' %}">Forgot Password?</a>
				</fieldset>
		</form>
		<br><a href="{% url 'user:register' %}">Don't have an account then register</a>
	
	
	
	
{% endblock content %}

user/templates/login.html
{% extends "Base1.html" %}
{% load crispy_forms_tags %}
{% block content %}
	
		<form method="post">
		{% csrf_token %}
			<!-- page is divided into 12 column   -->
			<div class="container">
				<!-- page is repsented in the type of row  -->
				<div class="row">
					<!-- dividing the screen for small, medium and large screens -->
					<div class="col-sm-12 col-md-8 col-lg-6">
							<br><br><fieldset class="form-group">
							<legend>Login In</legend>
								{{ form|crispy }}
								<br><input class="btn btn-info btn-lg btn-block" type="submit" value="Login">
								<br><a href="{% url 'user:password_reset' %}">Forgot Password?</a>
							</fieldset>
					</div>
					<div class="col-sm-12 col-md-4 col-lg-6">
						<div class="facebook-login-align">
							<a class="btn btn-info" href="{% url 'social:begin' 'facebook' %}" style="width:300px">Login with facebook</a>
						</div>
					</div>
				</div>
					<br><a href="{% url 'user:register' %}">Don't have an account then registered here</a>
			</div>	
		</form>
		
	
	
	
	
{% endblock content %}

user/templates/password_reset_complete.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	
		 <div class="alert alert-info" role="alert">
		 	Your password has been set try <a href="{% url 'user:login' %}">signing in </a>
		 </div>
	
	
	
{% endblock content %}

user/templates/password_reset_confirm.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	
		<form method="post">
		{% csrf_token %}
				<br><br><fieldset>
				<legend>Provide details to change the password</legend>
					{{ form|crispy }}
					<br><input class="btn btn-info btn-lg btn-block" type="submit" value="Login">
				</fieldset>
		</form>	
	
	
	
{% endblock content %}

user/templates/password_reset_done.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	
		 <div class="alert alert-info" role="alert">
		 	An Email as been sent to your email id to reset your password
		 </div>
	
	
	
{% endblock content %}